### PR TITLE
Fins ido insurance

### PR DESCRIPTION
**Pull request by jorgepascoPE**

### CODE REVIEW

**Comment by ttse-sfdc** [comment]
@jorgepascoPE getting this error when trying to create this app 
image

**Comment by jorgepascoPE** [comment]
Yes! It depends on Wealth App, remember we talked about it? We never
decoupled it.

**Comment by jorgepascoPE** [comment]
Is it just a matter of deleting this? I'll do it
[image: image.png]

**Comment by jorgepascoPE** [comment]
Ok, it's working now.

**Pull request merged**
